### ISSUE TITLE
Keyboard navigation js error 404

### ISSUE THREAD

**Issue by DoubleYouGTT** [Fruitfulcode/Fruitful#31]
I've got my site setup to send me error 404 messages, and I get bombarded by a 404 from "/wp-content/themes/fruitful/js/keyboard-image-navigation.js?ver=20120202".

As there is no keyboard-image-navigation.js in the Fruitful repository, I traced the error back to functions.php line 321, where there IS a reference to this js. Happens for ALL images in a gallery.

**Comment by macmittereder** [comment]
Added the file to fix this issue

**Comment by yuriipavlov** [comment]
https://github.com/Fruitfulcode/Fruitful/pull/37
merged
Thanks!
