### ISSUE TITLE
Dequeue Google fonts

### ISSUE THREAD

**Issue by lonesomewalker** [Fruitfulcode/Fruitful#33]
Is it possible to include Google fonts directly in the theme?
In case of privacy, it would be better to include it instead of calling the fonts api.
Unfortunately, the function for the enqueue is not that easy to dequeue in childs function.php.

**Comment by yuriipavlov** [comment]
Hi!
Sorry for the late reply) What do you mean "directly in the theme"?

If you use child theme, you can add function fruitful_add_custom_fonts() or fruitful_check_gg_custom_fonts() in your child theme and make your own google fonts connection, or disable it. For example
function fruitful_add_custom_fonts() {
    return;
}

functions.php:418
