### ISSUE TITLE
FlexSlider disappeared on new update

### ISSUE THREAD

**Issue by jujujujuju45** [Fruitfulcode/Fruitful#38]
I just updated to the new version of the theme this morning and the FlexSlider disappeared from all pages.

**Comment by ilyapavlov** [comment]
Please go to theme options > slider and check settings in slide, should be active checkbox.

**Comment by icode4coffee** [comment]
Hi, I am having the same problem. 
Going to the settings shows the flexslider to be active.
Did you already manage to fix this bug @jujujujuju45 ?

**Comment by jujujujuju45** [comment]
Yes, I fixed it. I went back to THEME OPTIONS > SLIDER, and opened each slide, then I had to re-checked a box (can't exactly remember what the check box was about)....

**Comment by jujujujuju45** [comment]
<img width="743" alt="screen shot 2017-11-07 at 4 31 11 pm" src="https://user-images.githubusercontent.com/31963080/32523574-1c8066ee-c3d9-11e7-9088-121af1bfeef1.png">

Check the Active Box for each slides

**Comment by icode4coffee** [comment]
Woh thank you!
@ilyapavlov maybe its worth changing the description above the slider-settings since it is not correct anymore: "To display slider in needed place use shortcode [fruitful_slider]." and add that the "active" checkbox can get disabled after auto-upgrading?
