### ISSUE TITLE
Variable product problem

### ISSUE THREAD

**Issue by Ice6744** [Fruitfulcode/Fruitful#39]
Hi
After major store updates I cant get the product to change variable picture that is assigned. Price changes but not the picture. Change a theme and everything works...
Example:
http://shop.aftermarket.ee/toode/chevrolet-captiva-11-13/

Any ideas?

**Comment by BenneMe** [comment]
Hey,
i tried to copy the current file out of the woocommerce folder, then the image change seems to work, but the product image is very small...

**Comment by Ice6744** [comment]
No need for this anymore, thank you!

Siim
aftermarket.ee

**Comment by BenneMe** [comment]
@Ice6744 How did you solved the problem?

**Comment by yuriipavlov** [comment]
Hi!
We updated woocommerce templates and fixed this problem!
Also we updated woocommerce lightbox.
Please, update your theme to 3.6
https://github.com/Fruitfulcode/Fruitful/releases/tag/3.6

Thanks!
