### ISSUE TITLE
update cart button

### ISSUE THREAD

**Issue by melhendawy** [Fruitfulcode/Fruitful#41]
i have some issue on cart after update woocommerce  on update cart button 
and product pictures on responsive mode 

please check the  attachment 

thank you

![2](https://user-images.githubusercontent.com/36287414/36356139-956177a8-14fe-11e8-8407-3fb002ef740d.png)
![1](https://user-images.githubusercontent.com/36287414/36356140-958d4e14-14fe-11e8-9b56-49efbc4e3a55.png)

**Comment by yuriipavlov** [comment]
Thanks a lot!
Fixed https://github.com/Fruitfulcode/Fruitful/commit/cf345ed2d7894f0355c137cd089c9d6d7727d5a8
Good day!
